services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: orders_db
    volumes:
      - mongodb_data:/data/db

  mongo_inserter:
    image: python:3.11-slim
    container_name: mongo_inserter
    depends_on:
      - kafka
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: >
      bash -c "
      pip install pymongo kafka-python &&
      python consumer_to_mongo.py
      "

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: item_data

  spark:
    image: eclipse-temurin:17-jre-ubi9-minimal
    container_name: spark
    depends_on: 
      - kafka
      - postgres
    volumes:
      - .:/app
        #- spark_cache:/root/.cache/pip
    working_dir: /app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: >
      bash -c "
      microdnf update -y &&
      microdnf install -y python3 python3-pip &&
      pip install pyspark kafka-python numpy &&
      python3 parcel_aggregator_to_carrier.py
      "
      # pip install psycopg2-binary &&
    restart: "no"

  producer:
    image: python:3.11-slim
    container_name: producer
    depends_on:
      - kafka
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: >
      bash -c "
      pip install numpy kafka-python &&
      python producer.py
      "

  api-tracking-request:
    image: python:3.11-slim
    container_name: api-tracking-request
    depends_on:
      - kafka
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: >
      bash -c "
      pip install kafka-python pymongo requests &&
      python api/api_requests.py
      "

  carrier-api:
    image: python:3.11-slim
    container_name: carrier-api
    depends_on:
      - kafka
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: >
      bash -c "
      pip install pymongo requests fastapi uvicorn &&
      python api/carrier_api.py
      "

  status_receiver_api:
    image: python:3.11-slim
    container_name: status_receiver_api 
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    command: >
      bash -c "
      pip install pymongo requests fastapi uvicorn &&
      python api/status_receiver_api.py
      "

  carrier_status:
    image: python:3.11-slim
    container_name: carrier_status
    depends_on:
      - mongodb
      - status_receiver_api
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      pip install pymongo requests &&
      python api/carrier_status.py
      "

  postgres_inserter:
    image: python:3.11-slim
    container_name: postgres_inserter
    depends_on:
      - postgres 
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      pip install pymongo psycopg2-binary schedule numpy &&
      python3 insert_item_data.py &&
      python3 postgres_inserter.py
      "
      
volumes:
  mongodb_data:
